import React, { createContext, useState } from 'react';

export const CampusContext = createContext(null);

const NATIONAL_EMERGENCY = {
  police: "10111",
  ambulance: "10177",
  fire: "112",
  gbv_helpline: "0800 428 428",
  suicide_crisis: "0800 567 567",
  childline: "0800 055 555",
  poison_control: "0861 555 777"
};

const ALL_CAMPUSES = [
  // UNIVERSITIES - 26 PUBLIC
  {
    id: "vut",
    name: "Vaal University of Technology",
    shortName: "VUT",
    city: "Vanderbijlpark",
    province: "Gauteng",
    primaryColor: "#8B0000",
    coords: { lat: -26.7033, lng: 27.8400 },
    emergency: { security: "0169504911", medical: "0169504912", national: NATIONAL_EMERGENCY },
    email: "registrar@vut.ac.za",
    applicationUrl: "https://ienabler.vut.ac.za/pls/prodi41/w99pkg.mi_login",
    offices: {}
  },
  {
    id: "up",
    name: "University of Pretoria",
    shortName: "UP",
    city: "Pretoria",
    province: "Gauteng",
    primaryColor: "#003D7C",
    coords: { lat: -25.7545, lng: 28.2314 },
    emergency: { security: "0124202310", medical: "0124202311", national: NATIONAL_EMERGENCY },
    email: "registrar@up.ac.za",
    applicationUrl: "https://www.up.ac.za/online-application",
    offices: {}
  },
  {
    id: "wits",
    name: "University of the Witwatersrand",
    shortName: "Wits",
    city: "Braamfontein",
    province: "Gauteng",
    primaryColor: "#1B3A6B",
    coords: { lat: -26.1908, lng: 28.0300 },
    emergency: { security: "0117174444", medical: "0117174445", national: NATIONAL_EMERGENCY },
    email: "Marike.Bosman@wits.ac.za",
    applicationUrl: "https://self-service.wits.ac.za",
    offices: {}
  },
  {
    id: "uj",
    name: "University of Johannesburg",
    shortName: "UJ",
    city: "Auckland Park",
    province: "Gauteng",
    primaryColor: "#FF7F00",
    coords: { lat: -26.1833, lng: 28.0000 },
    emergency: { security: "0115591313", medical: "0115591314", national: NATIONAL_EMERGENCY },
    email: "admissions@uj.ac.za",
    applicationUrl: "https://www.uj.ac.za/apply",
    offices: {}
  },
  {
    id: "tut",
    name: "Tshwane University of Technology",
    shortName: "TUT",
    city: "Pretoria",
    province: "Gauteng",
    primaryColor: "#8B0000",
    coords: { lat: -25.7326, lng: 28.1626 },
    emergency: { security: "0123824444", medical: "0123824445", national: NATIONAL_EMERGENCY },
    email: "admission@tut.ac.za",
    applicationUrl: "https://ienabler.tut.ac.za/pls/prodi41/w99pkg.mi_login",
    offices: {}
  },
  {
    id: "smu",
    name: "Sefako Makgatho Health Sciences University",
    shortName: "SMU",
    city: "Ga-Rankuwa",
    province: "Gauteng",
    primaryColor: "#008080",
    coords: { lat: -25.6200, lng: 28.0167 },
    emergency: { security: "0125214111", medical: "0125214112", national: NATIONAL_EMERGENCY },
    email: "apply@smu.ac.za",
    applicationUrl: "https://www.smu.ac.za/students/apply/",
    offices: {}
  },
  {
    id: "unisa",
    name: "University of South Africa",
    shortName: "UNISA",
    city: "Pretoria",
    province: "Gauteng",
    primaryColor: "#007A4D",
    coords: { lat: -25.7677, lng: 28.1993 },
    emergency: { security: "0124293111", medical: "0124293112", national: NATIONAL_EMERGENCY },
    email: "study-info@unisa.ac.za",
    applicationUrl: "https://www.unisa.ac.za/sites/corporate/default/Apply-for-admission",
    offices: {}
  },
  {
    id: "uct",
    name: "University of Cape Town",
    shortName: "UCT",
    city: "Cape Town",
    province: "Western Cape",
    primaryColor: "#007FA4",
    coords: { lat: -33.9570, lng: 18.4610 },
    emergency: { security: "0216502222", medical: "0216502223", national: NATIONAL_EMERGENCY },
    email: "reg-records@uct.ac.za",
    applicationUrl: "https://applyonline.uct.ac.za",
    offices: {}
  },
  {
    id: "su",
    name: "Stellenbosch University",
    shortName: "SU",
    city: "Stellenbosch",
    province: "Western Cape",
    primaryColor: "#7B1A2D",
    coords: { lat: -33.9328, lng: 18.8644 },
    emergency: { security: "0218082333", medical: "0218082334", national: NATIONAL_EMERGENCY },
    email: "info@sun.ac.za",
    applicationUrl: "https://student.sun.ac.za",
    offices: {}
  },
  {
    id: "uwc",
    name: "University of the Western Cape",
    shortName: "UWC",
    city: "Bellville",
    province: "Western Cape",
    primaryColor: "#000080",
    coords: { lat: -33.9342, lng: 18.6240 },
    emergency: { security: "0219592244", medical: "0219592245", national: NATIONAL_EMERGENCY },
    email: "admissions@uwc.ac.za",
    applicationUrl: "https://www.uwc.ac.za/apply",
    offices: {}
  },
  {
    id: "cput",
    name: "Cape Peninsula University of Technology",
    shortName: "CPUT",
    city: "Cape Town",
    province: "Western Cape",
    primaryColor: "#000080",
    coords: { lat: -33.9325, lng: 18.6408 },
    emergency: { security: "0219596911", medical: "0219596912", national: NATIONAL_EMERGENCY },
    email: "registrar@cput.ac.za",
    applicationUrl: "https://www.cput.ac.za/study/apply",
    offices: {}
  },
  {
    id: "ukzn",
    name: "University of KwaZulu-Natal",
    shortName: "UKZN",
    city: "Durban",
    province: "KwaZulu-Natal",
    primaryColor: "#000",
    coords: { lat: -29.8691, lng: 30.9816 },
    emergency: { security: "0312601111", medical: "0312601112", national: NATIONAL_EMERGENCY },
    email: "enquiries@ukzn.ac.za",
    applicationUrl: "https://applications.ukzn.ac.za",
    offices: {}
  },
  {
    id: "dut",
    name: "Durban University of Technology",
    shortName: "DUT",
    city: "Durban",
    province: "KwaZulu-Natal",
    primaryColor: "#006400",
    coords: { lat: -29.8536, lng: 31.0051 },
    emergency: { security: "0313732111", medical: "0313732112", national: NATIONAL_EMERGENCY },
    email: "Registrar@dut.ac.za",
    applicationUrl: "https://www.dut.ac.za/student_portal/student_registration/",
    offices: {}
  },
  {
    id: "mut",
    name: "Mangosuthu University of Technology",
    shortName: "MUT",
    city: "Umlazi",
    province: "KwaZulu-Natal",
    primaryColor: "#008000",
    coords: { lat: -29.9706, lng: 30.8925 },
    emergency: { security: "0319077111", medical: "0319077112", national: NATIONAL_EMERGENCY },
    email: "info@mut.ac.za",
    applicationUrl: "https://www.mut.ac.za/apply/",
    offices: {}
  },
  {
    id: "unizulu",
    name: "University of Zululand",
    shortName: "UNIZULU",
    city: "KwaDlangezwa",
    province: "KwaZulu-Natal",
    primaryColor: "#8B4513",
    coords: { lat: -28.8583, lng: 31.8419 },
    emergency: { security: "0359026000", medical: "0359026001", national: NATIONAL_EMERGENCY },
    email: "gumedez@unizulu.ac.za",
    applicationUrl: "https://www.unizulu.ac.za/apply/",
    offices: {}
  },
  {
    id: "nwu",
    name: "North-West University",
    shortName: "NWU",
    city: "Potchefstroom",
    province: "North West",
    primaryColor: "#4B0082",
    coords: { lat: -26.6947, lng: 27.0936 },
    emergency: { security: "0182991111", medical: "0182991112", national: NATIONAL_EMERGENCY },
    email: "studies@nwu.ac.za",
    applicationUrl: "https://studies.nwu.ac.za/studies/apply",
    offices: {}
  },
  {
    id: "ufs",
    name: "University of the Free State",
    shortName: "UFS",
    city: "Bloemfontein",
    province: "Free State",
    primaryColor: "#003D7C",
    coords: { lat: -29.1109, lng: 26.1844 },
    emergency: { security: "0514012911", medical: "0514012912", national: NATIONAL_EMERGENCY },
    email: "registrar@ufs.ac.za",
    applicationUrl: "https://apply.ufs.ac.za",
    offices: {}
  },
  {
    id: "cut",
    name: "Central University of Technology",
    shortName: "CUT",
    city: "Bloemfontein",
    province: "Free State",
    primaryColor: "#000080",
    coords: { lat: -29.1217, lng: 26.2144 },
    emergency: { security: "0515073911", medical: "0515073912", national: NATIONAL_EMERGENCY },
    email: "registrar@cut.ac.za",
    applicationUrl: "https://www.cut.ac.za/application-process",
    offices: {}
  },
  {
    id: "nmu",
    name: "Nelson Mandela University",
    shortName: "NMU",
    city: "Gqeberha",
    province: "Eastern Cape",
    primaryColor: "#FF8C00",
    coords: { lat: -34.0089, lng: 25.6694 },
    emergency: { security: "0415041111", medical: "0415041112", national: NATIONAL_EMERGENCY },
    email: "registrar@mandela.ac.za",
    applicationUrl: "https://www.mandela.ac.za/Study-at-Mandela/Application",
    offices: {}
  },
  {
    id: "ru",
    name: "Rhodes University",
    shortName: "RU",
    city: "Makhanda",
    province: "Eastern Cape",
    primaryColor: "#4B2E83",
    coords: { lat: -33.3142, lng: 26.5203 },
    emergency: { security: "0466038999", medical: "0466039000", national: NATIONAL_EMERGENCY },
    email: "registrar@ru.ac.za",
    applicationUrl: "https://ross.ru.ac.za",
    offices: {}
  },
  {
    id: "ufh",
    name: "University of Fort Hare",
    shortName: "UFH",
    city: "Alice",
    province: "Eastern Cape",
    primaryColor: "#006400",
    coords: { lat: -32.7875, lng: 26.8456 },
    emergency: { security: "0406022011", medical: "0406022012", national: NATIONAL_EMERGENCY },
    email: "info@ufh.ac.za",
    applicationUrl: "https://www.ufh.ac.za/apply/",
    offices: {}
  },
  {
    id: "wsu",
    name: "Walter Sisulu University",
    shortName: "WSU",
    city: "Mthatha",
    province: "Eastern Cape",
    primaryColor: "#8B4513",
    coords: { lat: -31.5889, lng: 28.7741 },
    emergency: { security: "0475022844", medical: "0475022845", national: NATIONAL_EMERGENCY },
    email: "registrar@WSU.ac.za",
    applicationUrl: "https://www.wsu.ac.za/index.php/en/study-with-us/application",
    offices: {}
  },
  {
    id: "ul",
    name: "University of Limpopo",
    shortName: "UL",
    city: "Mankweng",
    province: "Limpopo",
    primaryColor: "#228B22",
    coords: { lat: -23.8861, lng: 29.7381 },
    emergency: { security: "0152689111", medical: "0152689112", national: NATIONAL_EMERGENCY },
    email: "enrolment@ul.ac.za",
    applicationUrl: "https://www.ul.ac.za/index.php?Entity=Apply%20Now",
    offices: {}
  },
  {
    id: "univen",
    name: "University of Venda",
    shortName: "UNIVEN",
    city: "Thohoyandou",
    province: "Limpopo",
    primaryColor: "#000080",
    coords: { lat: -22.9764, lng: 30.4447 },
    emergency: { security: "0159628000", medical: "0159628001", national: NATIONAL_EMERGENCY },
    email: "info@univen.ac.za",
    applicationUrl: "https://www.univen.ac.za/students/apply/",
    offices: {}
  },
  {
    id: "ump",
    name: "University of Mpumalanga",
    shortName: "UMP",
    city: "Mbombela",
    province: "Mpumalanga",
    primaryColor: "#DAA520",
    coords: { lat: -25.4361, lng: 30.9811 },
    emergency: { security: "0130020001", medical: "0130020002", national: NATIONAL_EMERGENCY },
    email: "info@ump.ac.za",
    applicationUrl: "https://www.ump.ac.za/Study-with-us/Application-Process",
    offices: {}
  },
  {
    id: "spu",
    name: "Sol Plaatje University",
    shortName: "SPU",
    city: "Kimberley",
    province: "Northern Cape",
    primaryColor: "#8B4513",
    coords: { lat: -28.7439, lng: 24.7622 },
    emergency: { security: "0534910000", medical: "0534910001", national: NATIONAL_EMERGENCY },
    email: "info@spu.ac.za",
    applicationUrl: "https://www.spu.ac.za/index.php/apply/",
    offices: {}
  },

  // TVET COLLEGES - 49 MAJOR CAMPUSES
  { id: "ekurhuleni_east_tvet", name: "Ekurhuleni East TVET College", shortName: "EEC", city: "Springs", province: "Gauteng", primaryColor: "#1E90FF", coords: { lat: -26.2708, lng: 28.4419 }, emergency: { security: "0117364400", medical: "0117364401", national: NATIONAL_EMERGENCY }, email: "info@eec.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "ekurhuleni_west_tvet", name: "Ekurhuleni West TVET College", shortName: "EWC", city: "Germiston", province: "Gauteng", primaryColor: "#1E90FF", coords: { lat: -26.2178, lng: 28.1694 }, emergency: { security: "0113231600", medical: "0113231601", national: NATIONAL_EMERGENCY }, email: "info@ewc.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "tshwane_north_tvet", name: "Tshwane North TVET College", shortName: "TNC", city: "Pretoria", province: "Gauteng", primaryColor: "#4169E1", coords: { lat: -25.6842, lng: 28.2336 }, emergency: { security: "0124011600", medical: "0124011601", national: NATIONAL_EMERGENCY }, email: "info@tnc.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "tshwane_south_tvet", name: "Tshwane South TVET College", shortName: "TSC", city: "Pretoria", province: "Gauteng", primaryColor: "#4682B4", coords: { lat: -25.7828, lng: 28.2753 }, emergency: { security: "0126608500", medical: "0126608501", national: NATIONAL_EMERGENCY }, email: "info@tsc.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "sedibeng_tvet", name: "Sedibeng TVET College", shortName: "STC", city: "Vereeniging", province: "Gauteng", primaryColor: "#5F9EA0", coords: { lat: -26.6731, lng: 27.9264 }, emergency: { security: "0164226645", medical: "0164226646", national: NATIONAL_EMERGENCY }, email: "info@sedcol.co.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "western_tvet", name: "Western TVET College", shortName: "WTC", city: "Randfontein", province: "Gauteng", primaryColor: "#6495ED", coords: { lat: -26.1831, lng: 27.7047 }, emergency: { security: "0116933600", medical: "0116933601", national: NATIONAL_EMERGENCY }, email: "info@westcol.co.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "central_jhb_tvet", name: "Central Johannesburg TVET College", shortName: "CJC", city: "Johannesburg", province: "Gauteng", primaryColor: "#00BFFF", coords: { lat: -26.2041, lng: 28.0473 }, emergency: { security: "0113516000", medical: "0113516001", national: NATIONAL_EMERGENCY }, email: "info@cjc.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "southwest_gauteng_tvet", name: "South West Gauteng TVET College", shortName: "SWGC", city: "Roodepoort", province: "Gauteng", primaryColor: "#87CEEB", coords: { lat: -26.1625, lng: 27.8725 }, emergency: { security: "0115278300", medical: "0115278301", national: NATIONAL_EMERGENCY }, email: "info@swgc.co.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "college_cape_town", name: "College of Cape Town", shortName: "CCT", city: "Cape Town", province: "Western Cape", primaryColor: "#20B2AA", coords: { lat: -33.9249, lng: 18.4241 }, emergency: { security: "0214622053", medical: "0214622054", national: NATIONAL_EMERGENCY }, email: "info@cct.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "false_bay_tvet", name: "False Bay TVET College", shortName: "FBTC", city: "Muizenberg", province: "Western Cape", primaryColor: "#008B8B", coords: { lat: -34.1081, lng: 18.4697 }, emergency: { security: "0217888373", medical: "0217888374", national: NATIONAL_EMERGENCY }, email: "info@falsebaycollege.co.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "northlink_tvet", name: "Northlink TVET College", shortName: "NLC", city: "Bellville", province: "Western Cape", primaryColor: "#48D1CC", coords: { lat: -33.9036, lng: 18.6297 }, emergency: { security: "0219709000", medical: "0219709001", national: NATIONAL_EMERGENCY }, email: "info@northlink.co.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "boland_tvet", name: "Boland TVET College", shortName: "BTC", city: "Stellenbosch", province: "Western Cape", primaryColor: "#00CED1", coords: { lat: -33.9361, lng: 18.8600 }, emergency: { security: "0218867111", medical: "0218867112", national: NATIONAL_EMERGENCY }, email: "info@bolandcollege.com", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "west_coast_tvet", name: "West Coast TVET College", shortName: "WCTC", city: "Vredenburg", province: "Western Cape", primaryColor: "#40E0D0", coords: { lat: -32.9100, lng: 17.9936 }, emergency: { security: "0224821143", medical: "0224821144", national: NATIONAL_EMERGENCY }, email: "info@westcoastcollege.co.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "south_cape_tvet", name: "South Cape TVET College", shortName: "SCC", city: "George", province: "Western Cape", primaryColor: "#AFEEEE", coords: { lat: -33.9639, lng: 22.4617 }, emergency: { security: "0448840359", medical: "0448840360", national: NATIONAL_EMERGENCY }, email: "info@scc.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "coastal_kzn_tvet", name: "Coastal KZN TVET College", shortName: "CKZN", city: "Durban", province: "KwaZulu-Natal", primaryColor: "#00CED1", coords: { lat: -29.8587, lng: 31.0218 }, emergency: { security: "0319057000", medical: "0319057001", national: NATIONAL_EMERGENCY }, email: "info@coastalkzn.co.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "elc_tvet", name: "Elangeni TVET College", shortName: "ETC", city: "Pinetown", province: "KwaZulu-Natal", primaryColor: "#40E0D0", coords: { lat: -29.8186, lng: 30.8528 }, emergency: { security: "0317166700", medical: "0317166701", national: NATIONAL_EMERGENCY }, email: "info@elangeni.co.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "thekwini_tvet", name: "Thekwini TVET College", shortName: "TTC", city: "Durban", province: "KwaZulu-Natal", primaryColor: "#AFEEEE", coords: { lat: -29.8579, lng: 31.0292 }, emergency: { security: "0312508400", medical: "0312508401", national: NATIONAL_EMERGENCY }, email: "info@thekwinicollege.co.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "umfolozi_tvet", name: "Umfolozi TVET College", shortName: "UTC", city: "Richards Bay", province: "KwaZulu-Natal", primaryColor: "#7FFFD4", coords: { lat: -28.7831, lng: 32.0372 }, emergency: { security: "0359029500", medical: "0359029501", national: NATIONAL_EMERGENCY }, email: "info@umfolozicollege.co.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "majuba_tvet", name: "Majuba TVET College", shortName: "MTC", city: "Newcastle", province: "KwaZulu-Natal", primaryColor: "#66CDAA", coords: { lat: -27.7583, lng: 29.9311 }, emergency: { security: "0343264888", medical: "0343264889", national: NATIONAL_EMERGENCY }, email: "info@majuba.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "mnambithi_tvet", name: "Mnambithi TVET College", shortName: "MNTC", city: "Ladysmith", province: "KwaZulu-Natal", primaryColor: "#8FBC8F", coords: { lat: -28.5561, lng: 29.7817 }, emergency: { security: "0366311100", medical: "0366311101", national: NATIONAL_EMERGENCY }, email: "info@mnambithi.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "esayidi_tvet", name: "Esayidi TVET College", shortName: "ETC", city: "Port Shepstone", province: "KwaZulu-Natal", primaryColor: "#3CB371", coords: { lat: -30.7419, lng: 30.4547 }, emergency: { security: "0396855400", medical: "0396855401", national: NATIONAL_EMERGENCY }, email: "info@esayidifet.co.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "orbit_tvet", name: "Orbit TVET College", shortName: "OTC", city: "Rustenburg", province: "North West", primaryColor: "#7FFFD4", coords: { lat: -25.6672, lng: 27.2422 }, emergency: { security: "0145928461", medical: "0145928462", national: NATIONAL_EMERGENCY }, email: "info@orbitcollege.co.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "vuselela_tvet", name: "Vuselela TVET College", shortName: "VTC", city: "Klerksdorp", province: "North West", primaryColor: "#66CDAA", coords: { lat: -26.8522, lng: 26.6653 }, emergency: { security: "0184067800", medical: "0184067801", national: NATIONAL_EMERGENCY }, email: "info@vuselelacollege.co.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "taletso_tvet", name: "Taletso TVET College", shortName: "TTC", city: "Mahikeng", province: "North West", primaryColor: "#2E8B57", coords: { lat: -25.8561, lng: 25.6381 }, emergency: { security: "0183842341", medical: "0183842342", national: NATIONAL_EMERGENCY }, email: "info@taletsofetcollege.co.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "goldfields_tvet", name: "Goldfields TVET College", shortName: "GTC", city: "Welkom", province: "Free State", primaryColor: "#8FBC8F", coords: { lat: -27.9697, lng: 26.7383 }, emergency: { security: "0579106000", medical: "0579106001", national: NATIONAL_EMERGENCY }, email: "info@goldfields.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "motheo_tvet", name: "Motheo TVET College", shortName: "MTC", city: "Bloemfontein", province: "Free State", primaryColor: "#3CB371", coords: { lat: -29.1211, lng: 26.2140 }, emergency: { security: "0514069300", medical: "0514069301", national: NATIONAL_EMERGENCY }, email: "info@motheotvet.co.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "maluti_tvet", name: "Maluti TVET College", shortName: "MLTC", city: "Phuthaditjhaba", province: "Free State", primaryColor: "#4682B4", coords: { lat: -28.5074, lng: 28.8078 }, emergency: { security: "0587136100", medical: "0587136101", national: NATIONAL_EMERGENCY }, email: "info@malutitvet.co.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "flavius_mareka_tvet", name: "Flavius Mareka TVET College", shortName: "FMTC", city: "Sasolburg", province: "Free State", primaryColor: "#FF4500", coords: { lat: -26.8167, lng: 27.8269 }, emergency: { security: "0169760829", medical: "0169760830", national: NATIONAL_EMERGENCY }, email: "info@flaviusmareka.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "buffalo_city_tvet", name: "Buffalo City TVET College", shortName: "BCC", city: "East London", province: "Eastern Cape", primaryColor: "#0066CC", coords: { lat: -33.0153, lng: 27.9116 }, emergency: { security: "0437221500", medical: "0437221501", national: NATIONAL_EMERGENCY }, email: "info@bccollege.co.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "port_elizabeth_tvet", name: "Port Elizabeth TVET College", shortName: "PEC", city: "Gqeberha", province: "Eastern Cape", primaryColor: "#000080", coords: { lat: -33.9608, lng: 25.6022 }, emergency: { security: "0415096300", medical: "0415096301", national: NATIONAL_EMERGENCY }, email: "info@pecollege.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "eastcape_midlands_tvet", name: "Eastcape Midlands TVET College", shortName: "EMTC", city: "Uitenhage", province: "Eastern Cape", primaryColor: "#32CD32", coords: { lat: -33.7583, lng: 25.3978 }, emergency: { security: "0419952000", medical: "0419952001", national: NATIONAL_EMERGENCY }, email: "info@emcollege.co.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "king_hinthsa_tvet", name: "King Hintsa TVET College", shortName: "KHTC", city: "Butterworth", province: "Eastern Cape", primaryColor: "#8B0000", coords: { lat: -32.3289, lng: 28.1497 }, emergency: { security: "0474016400", medical: "0474016401", national: NATIONAL_EMERGENCY }, email: "info@kinghintsacollege.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "ikhala_tvet", name: "Ikhala TVET College", shortName: "ITC", city: "Queenstown", province: "Eastern Cape", primaryColor: "#FF1493", coords: { lat: -31.8978, lng: 26.8753 }, emergency: { security: "0458382590", medical: "0458382591", national: NATIONAL_EMERGENCY }, email: "info@ikhala.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "ingwe_tvet", name: "Ingwe TVET College", shortName: "INGTC", city: "Mount Frere", province: "Eastern Cape", primaryColor: "#228B22", coords: { lat: -30.9128, lng: 28.9911 }, emergency: { security: "0392550346", medical: "0392550347", national: NATIONAL_EMERGENCY }, email: "info@ingwecollege.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "king_sabata_dalindyebo_tvet", name: "King Sabata Dalindyebo TVET College", shortName: "KSDTC", city: "Mthatha", province: "Eastern Cape", primaryColor: "#006400", coords: { lat: -31.5886, lng: 28.7844 }, emergency: { security: "0475361070", medical: "0475361071", national: NATIONAL_EMERGENCY }, email: "info@ksdtvetcollege.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "capricorn_tvet", name: "Capricorn TVET College", shortName: "CTC", city: "Polokwane", province: "Limpopo", primaryColor: "#228B22", coords: { lat: -23.9045, lng: 29.4689 }, emergency: { security: "0152978367", medical: "0152978368", national: NATIONAL_EMERGENCY }, email: "info@capricorncollege.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "waterberg_tvet", name: "Waterberg TVET College", shortName: "WTC", city: "Mokopane", province: "Limpopo", primaryColor: "#008B8B", coords: { lat: -24.1947, lng: 29.0097 }, emergency: { security: "0154918581", medical: "0154918582", national: NATIONAL_EMERGENCY }, email: "info@waterbergcollege.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "lephalale_tvet", name: "Lephalale TVET College", shortName: "LTC", city: "Lephalale", province: "Limpopo", primaryColor: "#CD853F", coords: { lat: -23.6644, lng: 27.7467 }, emergency: { security: "0147632252", medical: "0147632253", national: NATIONAL_EMERGENCY }, email: "info@lephalale.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "mopani_south_east_tvet", name: "Mopani South East TVET College", shortName: "MSETC", city: "Phalaborwa", province: "Limpopo", primaryColor: "#FFD700", coords: { lat: -23.9478, lng: 31.1333 }, emergency: { security: "0157815721", medical: "0157815722", national: NATIONAL_EMERGENCY }, email: "info@mopanicollege.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "letaba_tvet", name: "Letaba TVET College", shortName: "LTC", city: "Tzaneen", province: "Limpopo", primaryColor: "#32CD32", coords: { lat: -23.8311, lng: 30.1631 }, emergency: { security: "0153075440", medical: "0153075441", national: NATIONAL_EMERGENCY }, email: "info@letabafet.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "vhembe_tvet", name: "Vhembe TVET College", shortName: "VTC", city: "Makwarela", province: "Limpopo", primaryColor: "#6B8E23", coords: { lat: -22.9825, lng: 30.4844 }, emergency: { security: "0159633156", medical: "0159633157", national: NATIONAL_EMERGENCY }, email: "info@vhembecollege.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "ehlanzeni_tvet", name: "Ehlanzeni TVET College", shortName: "ETC", city: "Mbombela", province: "Mpumalanga", primaryColor: "#7CFC00", coords: { lat: -25.4753, lng: 30.9694 }, emergency: { security: "0137522100", medical: "0137522101", national: NATIONAL_EMERGENCY }, email: "info@ehlanzenicollege.co.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "nkangala_tvet", name: "Nkangala TVET College", shortName: "NTC", city: "Witbank", province: "Mpumalanga", primaryColor: "#ADFF2F", coords: { lat: -25.8778, lng: 29.2319 }, emergency: { security: "0136562000", medical: "0136562001", national: NATIONAL_EMERGENCY }, email: "info@nkangalafet.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "gert_sibande_tvet", name: "Gert Sibande TVET College", shortName: "GSTC", city: "Ermelo", province: "Mpumalanga", primaryColor: "#9ACD32", coords: { lat: -26.5281, lng: 29.9856 }, emergency: { security: "0177129040", medical: "0177129041", national: NATIONAL_EMERGENCY }, email: "info@gscollege.co.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "northern_cape_urban_tvet", name: "Northern Cape Urban TVET College", shortName: "NCUTC", city: "Kimberley", province: "Northern Cape", primaryColor: "#A0522D", coords: { lat: -28.7282, lng: 24.7499 }, emergency: { security: "0538392000", medical: "0538392001", national: NATIONAL_EMERGENCY }, email: "info@ncutvet.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "northern_cape_rural_tvet", name: "Northern Cape Rural TVET College", shortName: "NCRTC", city: "Upington", province: "Northern Cape", primaryColor: "#CD5C5C", coords: { lat: -28.4478, lng: 21.2561 }, emergency: { security: "0543313836", medical: "0543313837", national: NATIONAL_EMERGENCY }, email: "info@ncrtvet.com", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "esikhawini_tvet", name: "Esikhawini TVET College", shortName: "Esikhawini", city: "Empangeni", province: "KwaZulu-Natal", primaryColor: "#FF5722", coords: { lat: -28.8673, lng: 31.9114 }, emergency: { security: "0359029700", medical: "0359029701", national: NATIONAL_EMERGENCY }, email: "info@esikhawini.edu.za", applicationUrl: "https://www.cao.ac.za", offices: {} },
  { id: "mthashana_tvet", name: "Mthashana TVET College", shortName: "Mthashana", city: "Vryheid", province: "KwaZulu-Natal", primaryColor: "#9C27B0", coords: { lat: -27.7658, lng: 30.7983 }, emergency: { security: "0349801111", medical: "0349801112", national: NATIONAL_EMERGENCY }, email: "info@mthashanacollege.co.za", applicationUrl: "https://www.cao.ac.za", offices: {} },

  // PRIVATE INSTITUTIONS - 19
  {
    id: "varsity_college",
    name: "Varsity College",
    shortName: "VC",
    city: "National",
    province: "National",
    primaryColor: "#003DA5",
    coords: { lat: -26.1076, lng: 28.0567 },
    emergency: { security: "0861764822", medical: "0861764823", national: NATIONAL_EMERGENCY },
    email: "info@varsitycollege.co.za",
    applicationUrl: "https://www.varsitycollege.co.za/apply",
    offices: {}
  },
  {
    id: "rosebank_college",
    name: "Rosebank College",
    shortName: "Rosebank",
    city: "National",
    province: "National",
    primaryColor: "#7A1F3D",
    coords: { lat: -26.1450, lng: 28.0407 },
    emergency: { security: "0861403323", medical: "0861403324", national: NATIONAL_EMERGENCY },
    email: "info@rosebankcollege.co.za",
    applicationUrl: "https://www.rosebankcollege.co.za/apply",
    offices: {}
  },
  {
    id: "damelin",
    name: "Damelin",
    shortName: "Damelin",
    city: "National",
    province: "National",
    primaryColor: "#1C4E80",
    coords: { lat: -26.2708, lng: 28.1123 },
    emergency: { security: "0860613111", medical: "0860613112", national: NATIONAL_EMERGENCY },
    email: "info@damelin.co.za",
    applicationUrl: "https://www.damelin.co.za/apply",
    offices: {}
  },
  {
    id: "premier_college",
    name: "Premier College",
    shortName: "Premier",
    city: "Johannesburg",
    province: "Gauteng",
    primaryColor: "#FF6600",
    coords: { lat: -26.2041, lng: 28.0473 },
    emergency: { security: "0861117777", medical: "0861117778", national: NATIONAL_EMERGENCY },
    email: "info@premiercollege.co.za",
    applicationUrl: "https://www.premiercollege.co.za/apply",
    offices: {}
  },
  {
    id: "icb",
    name: "Institute of Certified Bookkeepers",
    shortName: "ICB",
    city: "Cape Town",
    province: "Western Cape",
    primaryColor: "#0066CC",
    coords: { lat: -33.9249, lng: 18.4241 },
    emergency: { security: "0212022500", medical: "0212022501", national: NATIONAL_EMERGENCY },
    email: "info@icb.org.za",
    applicationUrl: "https://www.icb.org.za/apply",
    offices: {}
  },
  {
    id: "boston_city_campus",
    name: "Boston City Campus",
    shortName: "Boston",
    city: "Johannesburg",
    province: "Gauteng",
    primaryColor: "#E60000",
    coords: { lat: -26.2041, lng: 28.0473 },
    emergency: { security: "0115303800", medical: "0115303801", national: NATIONAL_EMERGENCY },
    email: "info@boston.co.za",
    applicationUrl: "https://www.boston.co.za/apply",
    offices: {}
  },
  {
    id: "stadio",
    name: "STADIO Higher Education",
    shortName: "STADIO",
    city: "Johannesburg",
    province: "Gauteng",
    primaryColor: "#003366",
    coords: { lat: -26.1076, lng: 28.0567 },
    emergency: { security: "0871585000", medical: "0871585001", national: NATIONAL_EMERGENCY },
    email: "info@stadio.ac.za",
    applicationUrl: "https://www.stadio.ac.za/apply",
    offices: {}
  },
  {
    id: "milpark_education",
    name: "Milpark Education",
    shortName: "Milpark",
    city: "Johannesburg",
    province: "Gauteng",
    primaryColor: "#00529F",
    coords: { lat: -26.1929, lng: 28.0305 },
    emergency: { security: "0861119999", medical: "0861119998", national: NATIONAL_EMERGENCY },
    email: "info@milpark.ac.za",
    applicationUrl: "https://www.milpark.ac.za/apply",
    offices: {}
  },
  {
    id: "regent_business_school",
    name: "Regent Business School",
    shortName: "Regent",
    city: "Durban",
    province: "KwaZulu-Natal",
    primaryColor: "#009639",
    coords: { lat: -29.8587, lng: 31.0218 },
    emergency: { security: "0313044625", medical: "0313044626", national: NATIONAL_EMERGENCY },
    email: "info@regent.ac.za",
    applicationUrl: "https://www.regent.ac.za/apply",
    offices: {}
  },
  {
    id: "mancosa",
    name: "MANCOSA",
    shortName: "MANCOSA",
    city: "Durban",
    province: "KwaZulu-Natal",
    primaryColor: "#003D7C",
    coords: { lat: -29.8587, lng: 31.0218 },
    emergency: { security: "0313007200", medical: "0313007201", national: NATIONAL_EMERGENCY },
    email: "info@mancosa.co.za",
    applicationUrl: "https://www.mancosa.co.za/apply",
    offices: {}
  },
  {
    id: "regenesys",
    name: "Regenesys Business School",
    shortName: "Regenesys",
    city: "Sandton",
    province: "Gauteng",
    primaryColor: "#E30613",
    coords: { lat: -26.1076, lng: 28.0567 },
    emergency: { security: "0861999595", medical: "0861999596", national: NATIONAL_EMERGENCY },
    email: "info@regenesys.net",
    applicationUrl: "https://www.regenesys.net/apply",
    offices: {}
  },
  {
    id: "afda",
    name: "AFDA",
    shortName: "AFDA",
    city: "Johannesburg",
    province: "Gauteng",
    primaryColor: "#000",
    coords: { lat: -26.1929, lng: 28.0305 },
    emergency: { security: "0114825145", medical: "0114825146", national: NATIONAL_EMERGENCY },
    email: "info@afda.co.za",
    applicationUrl: "https://www.afda.co.za/apply",
    offices: {}
  },
  {
    id: "cti",
    name: "CTI Education Group",
    shortName: "CTI",
    city: "Johannesburg",
    province: "Gauteng",
    primaryColor: "#FF0000",
    coords: { lat: -26.2041, lng: 28.0473 },
    emergency: { security: "0861111284", medical: "0861111285", national: NATIONAL_EMERGENCY },
    email: "info@cti.ac.za",
    applicationUrl: "https://www.cti.ac.za/apply",
    offices: {}
  },
  {
    id: "imm",
    name: "IMM Graduate School",
    shortName: "IMM",
    city: "Johannesburg",
    province: "Gauteng",
    primaryColor: "#004B87",
    coords: { lat: -26.1929, lng: 28.0305 },
    emergency: { security: "0112680260", medical: "0112680261", national: NATIONAL_EMERGENCY },
    email: "info@imm.co.za",
    applicationUrl: "https://www.imm.co.za/apply",
    offices: {}
  },
  {
    id: "ase",
    name: "Academy of Sound Engineering",
    shortName: "ASE",
    city: "Johannesburg",
    province: "Gauteng",
    primaryColor: "#1A1A1A",
    coords: { lat: -26.1929, lng: 28.0305 },
    emergency: { security: "0117263610", medical: "0117263611", national: NATIONAL_EMERGENCY },
    email: "info@ase.co.za",
    applicationUrl: "https://www.ase.co.za/apply",
    offices: {}
  },
  {
    id: "lisof",
    name: "LISOF",
    shortName: "LISOF",
    city: "Johannesburg",
    province: "Gauteng",
    primaryColor: "#D4AF37",
    coords: { lat: -26.1929, lng: 28.0305 },
    emergency: { security: "0114031035", medical: "0114031036", national: NATIONAL_EMERGENCY },
    email: "info@lisof.co.za",
    applicationUrl: "https://www.lisof.co.za/apply",
    offices: {}
  },
  {
    id: "dssa",
    name: "Design School Southern Africa",
    shortName: "DSSA",
    city: "Cape Town",
    province: "Western Cape",
    primaryColor: "#FF6B35",
    coords: { lat: -33.9249, lng: 18.4241 },
    emergency: { security: "0214476023", medical: "0214476024", national: NATIONAL_EMERGENCY },
    email: "info@designschool.co.za",
    applicationUrl: "https://www.designschool.co.za/apply",
    offices: {}
  },
  {
    id: "oxbridge_academy",
    name: "Oxbridge Academy",
    shortName: "Oxbridge",
    city: "Stellenbosch",
    province: "Western Cape",
    primaryColor: "#003366",
    coords: { lat: -33.9328, lng: 18.8644 },
    emergency: { security: "0211100110", medical: "0211100111", national: NATIONAL_EMERGENCY },
    email: "info@oxbridgeacademy.edu.za",
    applicationUrl: "https://www.oxbridgeacademy.edu.za/apply",
    offices: {}
  }
];

export const CampusProvider = ({ children }) => {
  const [activeCampus, setActiveCampus] = useState(ALL_CAMPUSES[0]);
  const [isLoading, setIsLoading] = useState(false);

  return (
    <CampusContext.Provider value={{ activeCampus, setActiveCampus, isLoading, allCampuses: ALL_CAMPUSES }}>
      {children}
    </CampusContext.Provider>
  );
};